{% set version = "1.7-2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-reldist
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/reldist_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/reldist/reldist_{{ version }}.tar.gz
  sha256: d9086cbc14ed7c65d72da285b86a07e77cbfebc478ba7327b769bd08549229c9

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-densestbayes
    - r-mgcv
  run:
    - r-base
    - r-densestbayes
    - r-mgcv

test:
  commands:
    - $R -e "library('reldist')"           # [not win]
    - "\"%R%\" -e \"library('reldist')\""  # [win]

about:
  home: http://www.stat.ucla.edu/~handcock/RelDist
  license: GPL-3.0-only
  summary: Tools for the comparison of distributions. This includes nonparametric estimation of the relative distribution PDF and CDF and numerical summaries as described in "Relative Distribution Methods in the Social Sciences" by Mark S. Handcock and Martina Morris, Springer-Verlag, 1999, Springer-Verlag, ISBN 0387987789.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: reldist
# Version: 1.6-6
# Date: 2016-10-07
# Title: Relative Distribution Methods
# Author: Mark S. Handcock <handcock@stat.ucla.edu>
# Maintainer: Mark S. Handcock <handcock@stat.ucla.edu>
# Description: Tools for the comparison of distributions. This includes nonparametric estimation of the relative distribution PDF and CDF and numerical summaries as described in "Relative Distribution Methods in the Social Sciences" by Mark S. Handcock and Martina Morris, Springer-Verlag, 1999, Springer-Verlag, ISBN 0387987789.
# Imports: mgcv, Hmisc
# Suggests: locfit
# License: GPL-3 + file LICENSE
# URL: http://www.stat.ucla.edu/~handcock/RelDist
# NeedsCompilation: no
# Packaged: 2016-10-09 17:00:10 UTC; handcock
# Repository: CRAN
# Date/Publication: 2016-10-09 19:48:45
