appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: MjM8QkjDWpB4bZCpIFDKFAW2r4iA1nQW+rAiVOoeSg0KxdgHbUp5cJQd0UkoU36FKe6F+g7GR0fVGiIgFBMceuzjdfpfTSqIAneBjRaWQ0V6JQUf6vA9tRyvGHRMC7RGPjqPen2CeNdIrKt2McZwQY1ccBSUBeTCAJAuy1oEOhJD9xIZoa+NIAg12dCGwlW5mogmfs3lYfi542x7uF7Ltgz3qb7+3LJxmiHBHUNBZ6h0E22ktlfo8kVaox5G6cNmgUrU6dL6efdpkfr1Rjql4Ud/NvUI9b6wCnBvrNyODXPcaJ3at61/2R8WZPUYqR86sOLFmMJLzI6DjHKKDXWBjTEXz37LbauIpaIFBbnTO8SsXI4EqBdXWIOKwgFRyCF+DhaKRqTQNh7MbVJr4cv9fJKHsORJ11uBxnDt0OlwBXFssg9q+cmL5ed0zeTr+zcRX/4DIBi9pWXXawKJVTnlvPfDKipCOt/piagFKXOEYN63vXQT1SMuispowtojJLC2ydI00cSCNNuY+IsQ9CvlmFSgI6kRHNOKPCVLmfIV/AP29PIv8z1/7rO3tjS9bvr7fbGKHTV8z1zKPKG1s5aA7slwcDgflEBcvgl0aaOQyAgxizACqVc4Lr/gH3+RFYCz24Bl7+HQDdeyAb3+8tWDSAHm3bwdiQt56MpMcqZF2DE=
conda_forge_output_validation: false
